import React from 'react';
import { Wallet, X, Trash2 } from 'lucide-react';

export default function BettingCardModal({ isOpen, onClose, bets, onDeleteBet, onUpdateBet }) {
  if(!isOpen) return null;
  const gradedBets = bets.filter(b => b.status !== 'pending');
  const totalWagered = gradedBets.reduce((sum, b) => sum + b.units, 0);
  const totalProfit = gradedBets.reduce((sum, b) => { if (b.status === 'win') return sum + (b.odds > 0 ? b.units * (b.odds / 100) : b.units * (100 / Math.abs(b.odds))); if (b.status === 'loss') return sum - b.units; return sum; }, 0);
  const roi = totalWagered > 0 ? ((totalProfit / totalWagered) * 100).toFixed(1) : "0.0";
  return (
    <div className="fixed inset-0 bg-black/90 z-50 flex items-center justify-center p-4"><div className="bg-gray-900 border border-gray-700 rounded-xl w-full max-w-2xl"><div className="p-4 border-b border-gray-800 flex justify-between"><div className="flex gap-2 text-emerald-400"><Wallet/><h3 className="font-bold">My Bets</h3></div><button onClick={onClose}><X/></button></div><div className="p-6"><div className="grid grid-cols-3 gap-4 mb-6"><div className="bg-gray-800 p-3 rounded border border-gray-700 text-center"><div className="text-xs text-gray-500 uppercase">Bets</div><div className="text-xl font-bold text-white">{bets.length}</div></div><div className="bg-gray-800 p-3 rounded border border-gray-700 text-center"><div className="text-xs text-gray-500 uppercase">Record</div><div className="text-xl font-bold text-white">{gradedBets.filter(b=>b.status==='win').length}-{gradedBets.filter(b=>b.status==='loss').length}</div></div><div className="bg-gray-800 p-3 rounded border border-gray-700 text-center"><div className="text-xs text-gray-500 uppercase">ROI</div><div className={`text-xl font-bold ${totalProfit >= 0 ? 'text-emerald-400' : 'text-red-400'}`}>{roi}%</div></div></div><div className="space-y-3 max-h-[50vh] overflow-y-auto">{bets.map(b=>(<div key={b.id} className="flex justify-between items-center bg-gray-800/50 p-3 rounded border border-gray-700"><div><div className="font-bold text-white">{b.selection} ({b.line > 0 && b.type==='spread' ? '+' : ''}{b.line})</div><div className="text-xs text-gray-500">{b.matchup} • {b.type.toUpperCase()} @ {b.odds > 0 ? '+' : ''}{b.odds}</div></div><div className="flex gap-3 items-center"><div className="flex items-center bg-gray-900 rounded border border-gray-600"><input type="number" value={b.units} onChange={(e)=>onUpdateBet(b.id, {units: parseFloat(e.target.value)})} className="w-10 bg-transparent text-center text-white text-xs p-1"/><span className="text-xs text-gray-500 pr-2">u</span></div><span className={`px-2 py-1 rounded text-xs uppercase font-bold ${b.status==='win'?'bg-emerald-900 text-emerald-400':b.status==='loss'?'bg-red-900 text-red-400':'bg-blue-900 text-blue-300'}`}>{b.status}</span><button onClick={()=>onDeleteBet(b.id)} className="text-gray-500 hover:text-red-400"><Trash2 size={14}/></button></div></div>))}</div></div></div></div>
  );
}